Iss12
keeperdao/landing-new pull request #14
Opened 2021-11-27 22:31 UTC by ptrrdrck

Branched from `next12upgrade`. Contains styling updates outlined in issue #12.

2021-11-27 23:27 UTC, pangolin1 requested changes
Looks mostly good, great on mobile. Left one suggestion in the code and would also fix the grid layouts here:

<img width="788" alt="Screen Shot 2021-11-27 at 6 23 16 PM" src="https://user-images.githubusercontent.com/87951552/143723193-0eaf54c5-35cb-4d26-a296-a7f5796d3f80.png">

The top 2 paragraphs should be column direction, bold text on top of normal text (like it is on mobile). 

Below, just make sure the trade, borrow, earn divs are the same height and line up.

2021-11-27 23:27 UTC, pangolin1 commented on src/Header.js
> +                Enter App
```suggestion
                App
```
I don't think we need the word "enter" here, "blog - abut - app" is fine

2021-11-28 00:06 UTC, pangolin1 commented on src/Header.js
> +                Enter App
on second thoughts, this is fine

2021-11-28 21:01 UTC, Pai-Sho commented
Are we intentionally getting rid of the gradient animation on these buttons? 

https://user-images.githubusercontent.com/26280070/143785843-91904e61-1c42-4613-b9c6-b33b7e5d9f20.mov

2021-11-28 21:03 UTC, Pai-Sho commented
Current behavior for reference

https://user-images.githubusercontent.com/26280070/143785871-5edd4a60-9fdc-4c4a-807a-aeaea64f8b07.mov

2021-11-28 21:11 UTC, Pai-Sho commented
Styling has been removed on some buttons

<img width="445" alt="Screen Shot 2021-11-28 at 2 10 40 PM" src="https://user-images.githubusercontent.com/26280070/143786088-bf905f22-ad56-43f5-be2e-28d9b2e2678b.png">

2021-11-28 21:18 UTC, ptrrdrck commented
Yes this was intentional as that button is now self-animating its gradient. When applying the new animation I opted to mimic the state styles of the Enter App button above for continuity. This button's hover state matches the above's default, and the active states also match. I feel it looks better than jumping to a new gradient state on hover, but I'm happy to try alts. I will check on the removed styling - is that ss hiding-book.js?

2021-11-29 17:22 UTC, pangolin1 commented
This is looking good. One last major thing I'd like addressed. 

This is the landing page on my browser (16inch laptop screen):
<img width="1536" alt="Screen Shot 2021-11-29 at 12 18 41 PM" src="https://user-images.githubusercontent.com/87951552/143913438-75e84956-f3a4-49cf-9fe8-536930a486a1.png">

I don't like that the copy is cut off at the bottom of the screen. Can address this in 2 ways:
- stretch the div out to the same width as the div above it (i think this will look better anyway)
- maybe tweak the vertical spacing (it also looks a bit gappy on mobile between some of the grid elements)

You also have the option of stretching out the width of the whole page, which runs a little narrow on desktop.

2021-11-30 00:27 UTC, pangolin1 approved these changes

2021-11-30 00:27 UTC, merged